[package]
name = "bytearray-ringbuffer"
version = "0.4.0"
edition = "2024"
rust-version = "1.85"
authors = ["Martin Pittermann"]
license = "MIT OR Apache-2.0"
description = "A no_std, no-alloc ring buffer for variable-length byte slices in Rust"
documentation = "https://docs.rs/bytearray-ringbuffer"
repository = "https://github.com/martin2250/bytearray-ringbuffer"
readme = "README.md"
keywords = ["no_std", "no-alloc", "heapless", "embedded", "ringbuffer"]
categories = ["data-structures", "no-std::no-alloc"]

[dependencies]
